// Auto-generated by Tools/build/generate_opcode_h.py from Lib/opcode.py

#ifndef Py_OPCODE_H
#define Py_OPCODE_H
#ifdef __cplusplus
extern "C" {
#endif


/* Instruction opcodes for compiled code */

#define PY_OPCODES(X) \
  X(CACHE,                           0) \
  X(POP_TOP,                         1) \
  X(PUSH_NULL,                       2) \
  X(NOP,                             9) \
  X(UNARY_POSITIVE,                 10) \
  X(UNARY_NEGATIVE,                 11) \
  X(UNARY_NOT,                      12) \
  X(UNARY_INVERT,                   15) \
  X(BINARY_SUBSCR,                  25) \
  X(GET_LEN,                        30) \
  X(MATCH_MAPPING,                  31) \
  X(MATCH_SEQUENCE,                 32) \
  X(MATCH_KEYS,                     33) \
  X(PUSH_EXC_INFO,                  35) \
  X(CHECK_EXC_MATCH,                36) \
  X(CHECK_EG_MATCH,                 37) \
  X(WITH_EXCEPT_START,              49) \
  X(GET_AITER,                      50) \
  X(GET_ANEXT,                      51) \
  X(BEFORE_ASYNC_WITH,              52) \
  X(BEFORE_WITH,                    53) \
  X(END_ASYNC_FOR,                  54) \
  X(STORE_SUBSCR,                   60) \
  X(DELETE_SUBSCR,                  61) \
  X(GET_ITER,                       68) \
  X(GET_YIELD_FROM_ITER,            69) \
  X(PRINT_EXPR,                     70) \
  X(LOAD_BUILD_CLASS,               71) \
  X(LOAD_ASSERTION_ERROR,           74) \
  X(RETURN_GENERATOR,               75) \
  X(LIST_TO_TUPLE,                  82) \
  X(RETURN_VALUE,                   83) \
  X(IMPORT_STAR,                    84) \
  X(SETUP_ANNOTATIONS,              85) \
  X(YIELD_VALUE,                    86) \
  X(ASYNC_GEN_WRAP,                 87) \
  X(PREP_RERAISE_STAR,              88) \
  X(POP_EXCEPT,                     89) \
  X(HAVE_ARGUMENT,                  90) \
  X(STORE_NAME,                     90) \
  X(DELETE_NAME,                    91) \
  X(UNPACK_SEQUENCE,                92) \
  X(FOR_ITER,                       93) \
  X(UNPACK_EX,                      94) \
  X(STORE_ATTR,                     95) \
  X(DELETE_ATTR,                    96) \
  X(STORE_GLOBAL,                   97) \
  X(DELETE_GLOBAL,                  98) \
  X(SWAP,                           99) \
  X(LOAD_CONST,                    100) \
  X(LOAD_NAME,                     101) \
  X(BUILD_TUPLE,                   102) \
  X(BUILD_LIST,                    103) \
  X(BUILD_SET,                     104) \
  X(BUILD_MAP,                     105) \
  X(LOAD_ATTR,                     106) \
  X(COMPARE_OP,                    107) \
  X(IMPORT_NAME,                   108) \
  X(IMPORT_FROM,                   109) \
  X(JUMP_FORWARD,                  110) \
  X(JUMP_IF_FALSE_OR_POP,          111) \
  X(JUMP_IF_TRUE_OR_POP,           112) \
  X(POP_JUMP_FORWARD_IF_FALSE,     114) \
  X(POP_JUMP_FORWARD_IF_TRUE,      115) \
  X(LOAD_GLOBAL,                   116) \
  X(IS_OP,                         117) \
  X(CONTAINS_OP,                   118) \
  X(RERAISE,                       119) \
  X(COPY,                          120) \
  X(BINARY_OP,                     122) \
  X(SEND,                          123) \
  X(LOAD_FAST,                     124) \
  X(STORE_FAST,                    125) \
  X(DELETE_FAST,                   126) \
  X(POP_JUMP_FORWARD_IF_NOT_NONE,  128) \
  X(POP_JUMP_FORWARD_IF_NONE,      129) \
  X(RAISE_VARARGS,                 130) \
  X(GET_AWAITABLE,                 131) \
  X(MAKE_FUNCTION,                 132) \
  X(BUILD_SLICE,                   133) \
  X(JUMP_BACKWARD_NO_INTERRUPT,    134) \
  X(MAKE_CELL,                     135) \
  X(LOAD_CLOSURE,                  136) \
  X(LOAD_DEREF,                    137) \
  X(STORE_DEREF,                   138) \
  X(DELETE_DEREF,                  139) \
  X(JUMP_BACKWARD,                 140) \
  X(CALL_FUNCTION_EX,              142) \
  X(EXTENDED_ARG,                  144) \
  X(LIST_APPEND,                   145) \
  X(SET_ADD,                       146) \
  X(MAP_ADD,                       147) \
  X(LOAD_CLASSDEREF,               148) \
  X(COPY_FREE_VARS,                149) \
  X(RESUME,                        151) \
  X(MATCH_CLASS,                   152) \
  X(FORMAT_VALUE,                  155) \
  X(BUILD_CONST_KEY_MAP,           156) \
  X(BUILD_STRING,                  157) \
  X(LOAD_METHOD,                   160) \
  X(LIST_EXTEND,                   162) \
  X(SET_UPDATE,                    163) \
  X(DICT_MERGE,                    164) \
  X(DICT_UPDATE,                   165) \
  X(PRECALL,                       166) \
  X(CALL,                          171) \
  X(KW_NAMES,                      172) \
  X(POP_JUMP_BACKWARD_IF_NOT_NONE, 173) \
  X(POP_JUMP_BACKWARD_IF_NONE,     174) \
  X(POP_JUMP_BACKWARD_IF_FALSE,    175) \
  X(POP_JUMP_BACKWARD_IF_TRUE,     176) \
  X(INVOKE_METHOD,                 185) \
  X(LOAD_FIELD,                    186) \
  X(LOAD_OBJ_FIELD,                187) \
  X(LOAD_PRIMITIVE_FIELD,          188) \
  X(STORE_FIELD,                   189) \
  X(STORE_OBJ_FIELD,               190) \
  X(STORE_PRIMITIVE_FIELD,         191) \
  X(BUILD_CHECKED_LIST,            192) \
  X(BUILD_CHECKED_LIST_CACHED,     193) \
  X(LOAD_TYPE,                     194) \
  X(CAST,                          195) \
  X(CAST_CACHED,                   196) \
  X(LOAD_LOCAL,                    197) \
  X(STORE_LOCAL,                   198) \
  X(STORE_LOCAL_CACHED,            199) \
  X(PRIMITIVE_BOX,                 200) \
  X(POP_JUMP_IF_ZERO,              201) \
  X(POP_JUMP_IF_NONZERO,           202) \
  X(PRIMITIVE_UNBOX,               203) \
  X(PRIMITIVE_BINARY_OP,           204) \
  X(PRIMITIVE_UNARY_OP,            205) \
  X(PRIMITIVE_COMPARE_OP,          206) \
  X(LOAD_ITERABLE_ARG,             207) \
  X(LOAD_MAPPING_ARG,              208) \
  X(INVOKE_FUNCTION,               209) \
  X(INVOKE_FUNCTION_CACHED,        210) \
  X(INVOKE_INDIRECT_CACHED,        211) \
  X(JUMP_IF_ZERO_OR_POP,           212) \
  X(JUMP_IF_NONZERO_OR_POP,        213) \
  X(FAST_LEN,                      214) \
  X(CONVERT_PRIMITIVE,             215) \
  X(INVOKE_NATIVE,                 216) \
  X(LOAD_CLASS,                    217) \
  X(BUILD_CHECKED_MAP,             218) \
  X(BUILD_CHECKED_MAP_CACHED,      219) \
  X(SEQUENCE_GET,                  220) \
  X(SEQUENCE_SET,                  221) \
  X(LIST_DEL,                      222) \
  X(REFINE_TYPE,                   223) \
  X(PRIMITIVE_LOAD_CONST,          224) \
  X(RETURN_PRIMITIVE,              225) \
  X(TP_ALLOC,                      226) \
  X(TP_ALLOC_CACHED,               227) \
  X(LOAD_METHOD_STATIC,            228) \
  X(LOAD_METHOD_STATIC_CACHED,     230) \
  X(BINARY_OP_ADAPTIVE,              3) \
  X(BINARY_OP_ADD_FLOAT,             4) \
  X(BINARY_OP_ADD_INT,               5) \
  X(BINARY_OP_ADD_UNICODE,           6) \
  X(BINARY_OP_INPLACE_ADD_UNICODE,   7) \
  X(BINARY_OP_MULTIPLY_FLOAT,        8) \
  X(BINARY_OP_MULTIPLY_INT,         13) \
  X(BINARY_OP_SUBTRACT_FLOAT,       14) \
  X(BINARY_OP_SUBTRACT_INT,         16) \
  X(BINARY_SUBSCR_ADAPTIVE,         17) \
  X(BINARY_SUBSCR_DICT,             18) \
  X(BINARY_SUBSCR_GETITEM,          19) \
  X(BINARY_SUBSCR_LIST_INT,         20) \
  X(BINARY_SUBSCR_TUPLE_INT,        21) \
  X(CALL_ADAPTIVE,                  22) \
  X(CALL_PY_EXACT_ARGS,             23) \
  X(CALL_PY_WITH_DEFAULTS,          24) \
  X(COMPARE_OP_ADAPTIVE,            26) \
  X(COMPARE_OP_FLOAT_JUMP,          27) \
  X(COMPARE_OP_INT_JUMP,            28) \
  X(COMPARE_OP_STR_JUMP,            29) \
  X(EXTENDED_ARG_QUICK,             34) \
  X(JUMP_BACKWARD_QUICK,            38) \
  X(LOAD_ATTR_ADAPTIVE,             39) \
  X(LOAD_ATTR_INSTANCE_VALUE,       40) \
  X(LOAD_ATTR_MODULE,               41) \
  X(LOAD_ATTR_SLOT,                 42) \
  X(LOAD_ATTR_WITH_HINT,            43) \
  X(LOAD_CONST__LOAD_FAST,          44) \
  X(LOAD_FAST__LOAD_CONST,          45) \
  X(LOAD_FAST__LOAD_FAST,           46) \
  X(LOAD_GLOBAL_ADAPTIVE,           47) \
  X(LOAD_GLOBAL_BUILTIN,            48) \
  X(LOAD_GLOBAL_MODULE,             55) \
  X(LOAD_METHOD_ADAPTIVE,           56) \
  X(LOAD_METHOD_CLASS,              57) \
  X(LOAD_METHOD_MODULE,             58) \
  X(LOAD_METHOD_NO_DICT,            59) \
  X(LOAD_METHOD_WITH_DICT,          62) \
  X(LOAD_METHOD_WITH_VALUES,        63) \
  X(PRECALL_ADAPTIVE,               64) \
  X(PRECALL_BOUND_METHOD,           65) \
  X(PRECALL_BUILTIN_CLASS,          66) \
  X(PRECALL_BUILTIN_FAST_WITH_KEYWORDS, 67) \
  X(PRECALL_METHOD_DESCRIPTOR_FAST_WITH_KEYWORDS, 72          ) \
  X(PRECALL_NO_KW_BUILTIN_FAST,     73) \
  X(PRECALL_NO_KW_BUILTIN_O,        76) \
  X(PRECALL_NO_KW_ISINSTANCE,       77) \
  X(PRECALL_NO_KW_LEN,              78) \
  X(PRECALL_NO_KW_LIST_APPEND,      79) \
  X(PRECALL_NO_KW_METHOD_DESCRIPTOR_FAST, 80  ) \
  X(PRECALL_NO_KW_METHOD_DESCRIPTOR_NOARGS, 81    ) \
  X(PRECALL_NO_KW_METHOD_DESCRIPTOR_O, 113) \
  X(PRECALL_NO_KW_STR_1,           121) \
  X(PRECALL_NO_KW_TUPLE_1,         127) \
  X(PRECALL_NO_KW_TYPE_1,          141) \
  X(PRECALL_PYFUNC,                143) \
  X(RESUME_QUICK,                  150) \
  X(STORE_ATTR_ADAPTIVE,           153) \
  X(STORE_ATTR_INSTANCE_VALUE,     154) \
  X(STORE_ATTR_SLOT,               158) \
  X(STORE_ATTR_WITH_HINT,          159) \
  X(STORE_FAST__LOAD_FAST,         161) \
  X(STORE_FAST__STORE_FAST,        167) \
  X(STORE_SUBSCR_ADAPTIVE,         168) \
  X(STORE_SUBSCR_DICT,             169) \
  X(STORE_SUBSCR_LIST_INT,         170) \
  X(UNPACK_SEQUENCE_ADAPTIVE,      177) \
  X(UNPACK_SEQUENCE_LIST,          178) \
  X(UNPACK_SEQUENCE_TUPLE,         179) \
  X(UNPACK_SEQUENCE_TWO_TUPLE,     180)

#define MIN_PSEUDO_OPCODE                      256
#define MAX_PSEUDO_OPCODE                      255

#define HAS_ARG(op) ((((op) >= HAVE_ARGUMENT) && (!IS_PSEUDO_OPCODE(op)))\
    )

#define HAS_CONST(op) (false\
    || ((op) == LOAD_CONST) \
    || ((op) == KW_NAMES) \
    || ((op) == INVOKE_METHOD) \
    || ((op) == LOAD_FIELD) \
    || ((op) == LOAD_OBJ_FIELD) \
    || ((op) == LOAD_PRIMITIVE_FIELD) \
    || ((op) == STORE_FIELD) \
    || ((op) == STORE_OBJ_FIELD) \
    || ((op) == STORE_PRIMITIVE_FIELD) \
    || ((op) == BUILD_CHECKED_LIST) \
    || ((op) == BUILD_CHECKED_LIST_CACHED) \
    || ((op) == LOAD_TYPE) \
    || ((op) == CAST) \
    || ((op) == CAST_CACHED) \
    || ((op) == LOAD_LOCAL) \
    || ((op) == STORE_LOCAL) \
    || ((op) == STORE_LOCAL_CACHED) \
    || ((op) == INVOKE_FUNCTION) \
    || ((op) == INVOKE_FUNCTION_CACHED) \
    || ((op) == INVOKE_INDIRECT_CACHED) \
    || ((op) == INVOKE_NATIVE) \
    || ((op) == LOAD_CLASS) \
    || ((op) == BUILD_CHECKED_MAP) \
    || ((op) == BUILD_CHECKED_MAP_CACHED) \
    || ((op) == REFINE_TYPE) \
    || ((op) == PRIMITIVE_LOAD_CONST) \
    || ((op) == TP_ALLOC) \
    || ((op) == TP_ALLOC_CACHED) \
    || ((op) == LOAD_METHOD_STATIC) \
    || ((op) == LOAD_METHOD_STATIC_CACHED) \
    )

#define NB_ADD                                   0
#define NB_AND                                   1
#define NB_FLOOR_DIVIDE                          2
#define NB_LSHIFT                                3
#define NB_MATRIX_MULTIPLY                       4
#define NB_MULTIPLY                              5
#define NB_REMAINDER                             6
#define NB_OR                                    7
#define NB_POWER                                 8
#define NB_RSHIFT                                9
#define NB_SUBTRACT                             10
#define NB_TRUE_DIVIDE                          11
#define NB_XOR                                  12
#define NB_INPLACE_ADD                          13
#define NB_INPLACE_AND                          14
#define NB_INPLACE_FLOOR_DIVIDE                 15
#define NB_INPLACE_LSHIFT                       16
#define NB_INPLACE_MATRIX_MULTIPLY              17
#define NB_INPLACE_MULTIPLY                     18
#define NB_INPLACE_REMAINDER                    19
#define NB_INPLACE_OR                           20
#define NB_INPLACE_POWER                        21
#define NB_INPLACE_RSHIFT                       22
#define NB_INPLACE_SUBTRACT                     23
#define NB_INPLACE_TRUE_DIVIDE                  24
#define NB_INPLACE_XOR                          25

/* Defined in Lib/opcode.py */
#define ENABLE_SPECIALIZATION 1
enum {
#define OP(op, value) op = value,
PY_OPCODES(OP)
#undef OP
};

#define IS_PSEUDO_OPCODE(op) (((op) >= MIN_PSEUDO_OPCODE) && ((op) <= MAX_PSEUDO_OPCODE))

#ifdef __cplusplus
}
#endif
#endif /* !Py_OPCODE_H */
