#!/usr/bin/env python3
"""Generate cinderx_ceval_extras.c from a pristine CPython v3.11.6 tree.

Mini borrow generator for the vendored 3.11 eval loop (design decision D3;
same philosophy as UpstreamBorrow's gen_cached files). The manylinux /
static-libpython runtime does not export a number of private helpers that
ceval.c, specialize.c and frame.c call; this tool copies their definitions
verbatim out of the upstream sources so the extraction is reproducible and
reviewable ("regenerate and diff" instead of trusting a hand copy).

Usage:
    extract_ceval_extras.py --upstream <cpython-3.11.6-tree> \
        [--out cinderx_ceval_extras.c]

The SYMBOLS table maps upstream file -> functions to extract, in order.
Static helpers that the extracted functions need are extracted the same way
and marked in the table. Everything is emitted verbatim; the only synthetic
lines are the section headers and the include prologue.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

# (upstream file, [symbol, ...]) in emission order. Order matters: statics
# must precede their users within a section, and sections must not reorder
# (some later sections use earlier ones, e.g. datastack helpers).
SYMBOLS: list[tuple[str, list[str]]] = [
    (
        "Objects/frameobject.c",
        [
            "_PyFrame_New_NoTrack",
            "_PyFrame_OpAlreadyRan",
            "_PyFrame_FastToLocalsWithError",
            "_PyFrame_LocalsToFast",
            "_PyEval_BuiltinsFromGlobals",
        ],
    ),
    (
        "Objects/listobject.c",
        ["list_resize", "_PyList_AppendTakeRefListResize"],
    ),
    (
        "Objects/funcobject.c",
        ["_PyFunction_FromConstructor", "_PyFunction_GetVersionForCurrentState"],
    ),
    (
        "Objects/codeobject.c",
        ["_PyCode_CreateLineArray"],
    ),
    (
        "Objects/genobject.c",
        [
            "typedef:_PyAsyncGenWrappedValue",
            "get_async_gen_state",
            "make_gen",
            "compute_cr_origin",
            "_Py_MakeCoro",
            "_PyAsyncGenValueWrapperNew",
        ],
    ),
    (
        "Objects/exceptions.c",
        [
            "typedef:_exceptiongroup_split_matcher_type",
            "typedef:_exceptiongroup_split_result",
            "_PyBaseExceptionGroupObject_cast",
            "is_same_exception_metadata",
            "exceptiongroup_split_check_match",
            "exceptiongroup_subset",
            "exceptiongroup_split_recursive",
            "collect_exception_group_leaf_ids",
            "exception_group_projection",
            "_PyExc_CreateExceptionGroup",
            "_PyExc_PrepReraiseStar",
        ],
    ),
    (
        "Objects/stringlib/eq.h",
        ["unicode_eq"],
    ),
    (
        "Objects/dictobject.c",
        [
            "unicode_get_hash",
            "dictkeys_get_index",
            "unicodekeys_lookup_unicode",
            "unicodekeys_lookup_generic",
            "dictkeys_generic_lookup",
            "_Py_dict_lookup",
            "_PyDictKeys_StringLookup",
            "_PyDict_GetItemHint",
            "_PyDictKeys_GetVersionForCurrentState",
        ],
    ),
    (
        "Python/pystate.c",
        [
            "allocate_chunk",
            "push_chunk",
            "_PyThreadState_BumpFramePointerSlow",
            "_PyThreadState_MustExit",
        ],
    ),
]

# Literal lines emitted at the start of a section: upstream in-file macros
# the extracted functions rely on (values copied verbatim from v3.11.6).
SECTION_PREFIX: dict[str, str] = {
    "Python/pystate.c": (
        "#define DATA_STACK_CHUNK_SIZE (16*1024)\n"
        "#define MINIMUM_OVERHEAD 1000\n"
    ),
    # Version allocators: upstream seeds these file-statics at 2/1 and they
    # are the only place the respective version fields are assigned. The
    # runtime's own allocator (invisible to us in static-libpython builds)
    # grows from the bottom of the uint32 space; ours is parked in the top
    # half so the two can never hand out the same version. On openEuler
    # (shared libpython) the formal port links the runtime statics'
    # exported accessors instead. See M2-log for the full analysis.
    "Objects/dictobject.c": (
        "#define DK_MASK(dk) (DK_SIZE(dk)-1)\n"
        "#define PERTURB_SHIFT 5\n"
        "static uint32_t next_dict_keys_version = ((uint32_t)1 << 31);\n"
    ),
    "Objects/funcobject.c": (
        "static uint32_t next_func_version = ((uint32_t)1 << 31);\n"
    ),
}


PROLOGUE = """\
// Copyright (c) Meta Platforms, Inc. and affiliates.
//
// GENERATED by extract_ceval_extras.py from pristine CPython v3.11.6
// sources -- DO NOT EDIT BY HAND. Regenerate with:
//
//   python3 extract_ceval_extras.py --upstream <cpython-v3.11.6-tree>
//
// These are private CPython helpers referenced by the vendored 3.11 eval
// loop (ceval/{ceval,specialize,frame}.c) that the target runtime may not
// export (observed on manylinux static-libpython builds). Function bodies
// are verbatim upstream; review by regenerating and diffing.

#define Py_BUILD_CORE

#include "Python.h"
#include "pycore_call.h"
#include "pycore_ceval.h"
#include "pycore_code.h"
#include "pycore_dict.h"
#include "pycore_floatobject.h"
#include "pycore_frame.h"
#include "pycore_function.h"
#include "pycore_genobject.h"
#include "pycore_list.h"
#include "pycore_long.h"
#include "pycore_moduleobject.h"
#include "pycore_exceptions.h"
#include "pycore_global_objects.h"
#include "pycore_opcode.h"
#include "pycore_pymem.h"
#include "pycore_runtime.h"
#include "pycore_object.h"
#include "pycore_pyerrors.h"
#include "pycore_pystate.h"
#include "pycore_tuple.h"
#include "frameobject.h"
#include "opcode.h"
#include "structmember.h"
"""


def extract_function(text: str, name: str, path: str) -> str:
    # Find a definition: `name(` at column 0 (CPython style puts the return
    # type on the previous line) or `static ... name(` one line above.
    # Match either CPython's usual style (return type on the previous line,
    # name at column 0) or a same-line return type (e.g. "uint32_t name(").
    pattern = re.compile(
        rf"^(?:[A-Za-z_][A-Za-z0-9_ ]*?[ *]+)?{re.escape(name)}\(", re.MULTILINE
    )
    match = None
    for candidate in pattern.finditer(text):
        # Reject prose hits inside comments: a real signature line ends with
        # '(' ',' or ')' (argument list), never with running text.
        line_end = text.find("\n", candidate.start())
        line = text[candidate.start() : line_end].rstrip()
        if not line.endswith(("(", ",", ")", "{")):
            continue
        # Skip forward declarations: a ';' before the first '{' means this
        # match is a prototype, not the definition.
        tail = text[candidate.start() :]
        brace_pos = tail.find("{")
        semi_pos = tail.find(";")
        if brace_pos != -1 and (semi_pos == -1 or brace_pos < semi_pos):
            match = candidate
            break
    if match is None:
        raise SystemExit(f"error: cannot find definition of {name} in {path}")
    start = match.start()
    # Pull in the return type / qualifiers: walk back over contiguous
    # non-empty lines that don't end in ';', '}' or start with '#'.
    lines_before = text[:start].splitlines(keepends=True)
    sig_prefix = []
    for line in reversed(lines_before):
        stripped = line.strip()
        if (
            not stripped
            or stripped.endswith((";", "}", "*/"))
            or stripped.startswith(("#", "//", "/*", "*"))
        ):
            break
        sig_prefix.append(line)
    prefix = "".join(reversed(sig_prefix))

    brace = text.index("{", start)
    depth = 0
    i = brace
    in_str = in_chr = in_line_comment = in_block_comment = False
    prev = ""
    while i < len(text):
        c = text[i]
        if in_line_comment:
            if c == "\n":
                in_line_comment = False
        elif in_block_comment:
            if prev == "*" and c == "/":
                in_block_comment = False
        elif in_str:
            if c == '"' and prev != "\\":
                in_str = False
        elif in_chr:
            if c == "'" and prev != "\\":
                in_chr = False
        elif prev == "/" and c == "/":
            in_line_comment = True
        elif prev == "/" and c == "*":
            in_block_comment = True
        elif c == '"':
            in_str = True
        elif c == "'":
            in_chr = True
        elif c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return prefix + text[start : i + 1] + "\n"
        prev = "" if prev == "\\" else c
        i += 1
    raise SystemExit(f"error: unbalanced braces extracting {name} from {path}")


def extract_typedef(text: str, name: str, path: str) -> str:
    """Extract a `typedef enum/struct { ... } name;` block verbatim."""
    terminator = re.compile(rf"^\}} {re.escape(name)};", re.MULTILINE)
    match = terminator.search(text)
    if match is None:
        raise SystemExit(f"error: cannot find typedef {name} in {path}")
    start = text.rfind("typedef", 0, match.start())
    if start == -1:
        raise SystemExit(f"error: no typedef keyword before {name} in {path}")
    return text[start : match.end()] + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--upstream", type=Path, required=True)
    parser.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).parent / "cinderx_ceval_extras.c",
    )
    args = parser.parse_args()

    chunks = [PROLOGUE]
    for rel, names in SYMBOLS:
        src = (args.upstream / rel).read_text()
        chunks.append(
            f"\n// ==== verbatim from {rel} (v3.11.6) ===================\n"
        )
        if rel in SECTION_PREFIX:
            chunks.append(SECTION_PREFIX[rel])
        for name in names:
            if name.startswith("typedef:"):
                chunks.append("\n" + extract_typedef(src, name[8:], rel))
            else:
                chunks.append("\n" + extract_function(src, name, rel))

    args.out.write_text("".join(chunks))
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
