fail_fast = true

[target]
python = "3.14"
arch = "arm64"
system = "Linux"

[[jobs]]
name = "runtime_tests"
kind = "runtime_tests"
coverage = true
[jobs.env]
CINDERX_LOCAL_DEPS = "{repo}/../cinderx-local-deps"
ENABLE_XXCLASSLOADER = "1"
